### ISSUE TITLE
redundant code for calling main C functions

### ISSUE THREAD

**Issue by steven-murray** [BradGreig/Hybrid21CM#10]
At this moment, every function (initial_conditions, perturb_field, etc.) has very similar structure (check inputs, try to read, run function, write). 

Most of this is basically boilerplate, which provides for bad coverage and updates. We should have a nicer system to deal with this.

**Comment by steven-murray** [comment]
I've pushed 2070c212778d9f1ba441fc7861db1068e1ca64db to partially fix that. 

As for the more general structure, I can't really see a good way to deal with this, other than going to a class-based format, which would require a lot of rethinking (especially for recursive operations). So for now, I say we just leave it (it works)

**Comment by BradGreig** [comment]
Yeah, I am comfortable with it being left as is. Especially given it is all working.
