### ISSUE TITLE
spin temperature at high redshift

### ISSUE THREAD

**Issue by steven-murray** [BradGreig/Hybrid21CM#16]
Running the following from cmd line:

``21CMMC spin 35 -- HII_DIM=35 DIM=70 BOX_LEN=50``

Gives a segfault, where the 35 is the redshift, which is equivalent to the Z_HEAT_MAX. Using 34.9 works fine. And so does 35.1. So it's just when the redshift is exactly the Z_HEAT_MAX that it segfaults.

**Comment by BradGreig** [comment]
Should be fixed with 9c72191707231d27398c80e17863f1211ade3328.
