### ISSUE TITLE
better way to do datafiles/noisefiles in likelihood

### ISSUE THREAD

**Issue by steven-murray** [BradGreig/Hybrid21CM#2]
At the moment, the likelihoods all expect that the simulate() will return a *list* of dicts, which accounts for the case where you might have several co-eval simulations at different redshifts (or different lightcone chunks), where the data should be saved in different files. However, this makes for a bit of awkwardness when writing likelihoods that have no need of multiple files (i.e. everything has to be zero-indexed before use). 

This should be dealt with consistently to provide a nicer way to write likelihoods.

**Comment by BradGreig** [comment]
It is not obvious to me at this point how one would deal with this. I reckon this might become obvious once we start playing around with it on larger-scales for different applications.

**Comment by steven-murray** [comment]
Closing due to it moving to the above referenced issue.
