### ISSUE TITLE
Docs for parameter ranges

### ISSUE THREAD

**Issue by steven-murray** [BradGreig/Hybrid21CM#22]
Need to add some documentation for how to choose parameter ranges for common configurations.

**Comment by steven-murray** [comment]
@BradGreig there is a section in the ``docs/faqs/MCMC_advanced_faq.ipynb`` where you could add this information.

**Comment by BradGreig** [comment]
Added some documentation to `docs/faqs` under the tab `Allowed parameter ranges` with commit 6bcbd0c
