### ISSUE TITLE
ability to globally set configuration

### ISSUE THREAD

**Issue by steven-murray** [BradGreig/Hybrid21CM#6]
It would be nice, at least for tests, to be able to globally set configuration options (eg. the box direc), rather than having to set it manually in each test. But we want to be able to do this without actually changing the file.

**Comment by BradGreig** [comment]
I'm not following this. Are you intending to test every single permutation? 

What do you mean by box direction. Do you mean choice of x, y or z coordinates? If so, you have to be careful to include conditionals. Lightcones and RSDs only really make sense along the line-of-sight direction (i.e. z direction). Using other directions should only be available for co-eval cubes.

**Comment by steven-murray** [comment]
Oh, sorry, I meant ``boxdir``, which is the default directory into which boxes are saved. Actually, at the moment I think that might be the only global configuration option, set in ``~/.21CMMC/config.yml``. To change that option globally, one can always overwrite this file. But it might be nice to be able to do this on a per-session basis, without touching the file. So when running tests, for example, boxes aren't written to the standard location, but a temp directory.

**Comment by BradGreig** [comment]
Oh, ok. Yeah, that makes a lot more sense!

**Comment by steven-murray** [comment]
Moved to above referenced issue
